### ISSUE TITLE
Any plans to implement sheet views?

### ISSUE THREAD

**Issue by k-risc** [stephenliberty/excel-builder.js#48]
It is my understanding, that the option to not show zero values (which you can set on a per-worksheet basis in Excel) is found in the XML in

    <sheetView showZeros="0" […]>
        […]
    </sheetView>

But it seems that excel-builder.js so far does not output sheetView nodes, therefore showZeros cannot be controlled.

Are there any plans to implement this?

**Comment by kfred** [comment]
+1 for this. sheetView node would also allow control over the showGridLines attribute.

**Comment by stephenliberty** [comment]
Per readme:

Contributing
-------------

Originally this project was sort of sponsored by a previous company I worked for. Unfortunately now it has no backing, and my time is very limited while I work on side projects to help make ends meet. If you use bountysource or contribute via paypal (to stephen@liberty-irm.com) to open up bounties on issues, it is very, very likely that I will add features and fix issues sooner than later.

Otherwise, if you have the ability to contribute yourself, please just do so as normal - I'll review and pull changes as they come in as quickly as I can.

**Comment by stephenliberty** [comment]
Implemented in V2. All excel sheet view and pane properties exposed.
